language: go
go:
    - 1.16

install:
    - go get -u honnef.co/go/tools/cmd/staticcheck
    - go get -v github.com/onsi/ginkgo/ginkgo
    - go get -v github.com/onsi/gomega
    - go get -v -t ./...
    - export PATH=$PATH:$HOME/gopath/bin

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --compilers=2
    - stage: "Static check"
      name: "staticcheck"
      script: staticcheck ./...
